import { NextResponse } from 'next/server'
import { z } from 'zod'
import { badRequest, spotifyErrorResponse } from '@/lib/api/respond'
import { isHostOf } from '@/lib/host/session'
import { currentSeatId } from '@/lib/player/session'
import { findEntryByNonce } from '@/lib/rooms/chain'
import { authorizePick, type PickTarget } from '@/lib/rooms/picking'
import { findRoomById } from '@/lib/rooms/repo'
import { findSeat } from '@/lib/rooms/seats'
import { submitPick } from '@/lib/rooms/submit'
import { readTurn } from '@/lib/rooms/turns'
import { fetchTrack } from '@/lib/spotify'

/**
 * Submit a pick.
 *
 * Takes a track *id* and an idempotency key, never the track's metadata: the
 * rules decide validity from the title and artists, so accepting those from
 * the browser would let anyone invent a matching word. The server re-fetches
 * the track from Spotify and re-validates from scratch.
 */
const BodySchema = z.object({
  trackId: z.string().regex(/^[A-Za-z0-9]{22}$/, 'trackId must be a Spotify track id'),
  /**
   * Generated by the client and reused across retries. This is what makes a
   * submit safe to repeat when the response was lost to bad signal.
   */
  nonce: z.string().min(8).max(128),
  /** Host-only: record the pick even though the rules rejected it. */
  override: z.boolean().optional(),
  /**
   * Pick on another seat's behalf: the driver says a song, somebody with a
   * free pair of hands types it. Only seats marked as having no phone can be
   * picked for, and the entry is credited to them rather than to the typist.
   */
  forSeatId: z.string().uuid().optional(),
})

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
): Promise<NextResponse> {
  const { id } = await params

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json(
      { error: 'invalid-request', message: 'Expected a JSON body.' },
      { status: 400 },
    )
  }

  const parsed = BodySchema.safeParse(body)
  if (!parsed.success) return badRequest(parsed.error)

  const room = await findRoomById(id)
  if (room === null) {
    return NextResponse.json({ error: 'no-room', message: 'Room not found.' }, { status: 404 })
  }
  if (room.status === 'ended') {
    return NextResponse.json(
      { error: 'room-ended', message: 'That game has finished.' },
      { status: 409 },
    )
  }
  if (room.status === 'paused') {
    return NextResponse.json(
      { error: 'room-paused', message: 'The host has paused the game.' },
      { status: 409 },
    )
  }

  /**
   * A replay is answered from the chain before anything else is judged.
   *
   * This has to come ahead of the turn check, not after it. When a submit
   * succeeds but its response is lost to bad signal, the turn has already
   * moved on -- so re-judging the retry rejects it as out of turn, which is
   * the one case the whole idempotency design exists to survive. The pick is
   * history by then; the only correct answer is the entry it created.
   */
  const alreadyApplied = await findEntryByNonce(id, parsed.data.nonce)
  if (alreadyApplied !== null) {
    return NextResponse.json({
      entry: alreadyApplied,
      turn: (await readTurn(id)) ?? { currentSeatId: null, turnStartedAt: null },
      wasDuplicate: true,
      queueWarning: null,
    })
  }

  const [callerSeatId, isHost, turn] = await Promise.all([
    currentSeatId(id),
    isHostOf(id),
    readTurn(id),
  ])
  const wantsOverride = parsed.data.override === true

  // Resolved here rather than inside the rules, so a seat from another room
  // or one that has been removed is a plain 404 and never a judgement call.
  let forSeat: PickTarget | null = null
  if (parsed.data.forSeatId !== undefined) {
    const target = await findSeat(parsed.data.forSeatId)
    if (target === null || target.roomId !== id || target.removedAt !== null) {
      return NextResponse.json(
        { error: 'no-such-seat', message: 'That player is not in this room.' },
        { status: 404 },
      )
    }
    forSeat = { id: target.id, name: target.name, hasPhone: target.hasPhone }
  }

  const allowed = authorizePick({
    callerSeatId,
    isHost,
    wantsOverride,
    forSeat,
    turn: turn ?? { currentSeatId: null, turnStartedAt: null },
    turnTimer: room.settings.turnTimer,
  })
  if (!allowed.ok) {
    return NextResponse.json(
      { error: allowed.error, message: allowed.message },
      { status: allowed.status },
    )
  }

  try {
    const track = await fetchTrack(parsed.data.trackId)
    if (track === null) {
      return NextResponse.json(
        { error: 'no-track', message: 'Spotify has no track with that id.' },
        { status: 404 },
      )
    }

    const outcome = await submitPick({
      room,
      track,
      seatId: allowed.seatId,
      clientNonce: parsed.data.nonce,
      override: wantsOverride,
      requireTurnAt: allowed.requireTurnAt,
    })

    if (!outcome.ok) {
      // Two people typing for the same phoneless seat is the normal case, not
      // an error in the request: one of them was always going to lose.
      if (outcome.reason === 'turn-moved') {
        return NextResponse.json(
          { error: 'turn-moved', message: 'Somebody got there first — that turn has gone.' },
          { status: 409 },
        )
      }

      // 422: the request was well-formed, the move was not legal.
      return NextResponse.json(
        {
          error: 'rejected',
          reason: outcome.result.valid ? null : outcome.result.reason,
          explanation: outcome.explanation,
        },
        { status: 422 },
      )
    }

    return NextResponse.json(
      {
        entry: outcome.entry,
        turn: outcome.turn,
        wasDuplicate: outcome.wasDuplicate,
        queueWarning: outcome.queueWarning,
      },
      { status: outcome.wasDuplicate ? 200 : 201 },
    )
  } catch (error) {
    return spotifyErrorResponse(error)
  }
}
