import { NextResponse } from 'next/server'
import { z } from 'zod'
import { badRequest, spotifyErrorResponse } from '@/lib/api/respond'
import { isHostOf } from '@/lib/host/session'
import { currentSeatId } from '@/lib/player/session'
import { findEntryByNonce } from '@/lib/rooms/chain'
import { findRoomById } from '@/lib/rooms/repo'
import { submitPick } from '@/lib/rooms/submit'
import { readTurn } from '@/lib/rooms/turns'
import { turnHasExpired } from '@/lib/rooms/turns'
import { fetchTrack } from '@/lib/spotify'

/**
 * Submit a pick.
 *
 * Takes a track *id* and an idempotency key, never the track's metadata: the
 * rules decide validity from the title and artists, so accepting those from
 * the browser would let anyone invent a matching word. The server re-fetches
 * the track from Spotify and re-validates from scratch.
 */
const BodySchema = z.object({
  trackId: z.string().regex(/^[A-Za-z0-9]{22}$/, 'trackId must be a Spotify track id'),
  /**
   * Generated by the client and reused across retries. This is what makes a
   * submit safe to repeat when the response was lost to bad signal.
   */
  nonce: z.string().min(8).max(128),
  /** Host-only: record the pick even though the rules rejected it. */
  override: z.boolean().optional(),
})

export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
): Promise<NextResponse> {
  const { id } = await params

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json(
      { error: 'invalid-request', message: 'Expected a JSON body.' },
      { status: 400 },
    )
  }

  const parsed = BodySchema.safeParse(body)
  if (!parsed.success) return badRequest(parsed.error)

  const room = await findRoomById(id)
  if (room === null) {
    return NextResponse.json({ error: 'no-room', message: 'Room not found.' }, { status: 404 })
  }
  if (room.status === 'ended') {
    return NextResponse.json(
      { error: 'room-ended', message: 'That game has finished.' },
      { status: 409 },
    )
  }
  if (room.status === 'paused') {
    return NextResponse.json(
      { error: 'room-paused', message: 'The host has paused the game.' },
      { status: 409 },
    )
  }

  /**
   * A replay is answered from the chain before anything else is judged.
   *
   * This has to come ahead of the turn check, not after it. When a submit
   * succeeds but its response is lost to bad signal, the turn has already
   * moved on -- so re-judging the retry rejects it as out of turn, which is
   * the one case the whole idempotency design exists to survive. The pick is
   * history by then; the only correct answer is the entry it created.
   */
  const alreadyApplied = await findEntryByNonce(id, parsed.data.nonce)
  if (alreadyApplied !== null) {
    return NextResponse.json({
      entry: alreadyApplied,
      turn: (await readTurn(id)) ?? { currentSeatId: null, turnStartedAt: null },
      wasDuplicate: true,
      queueWarning: null,
    })
  }

  const [seatId, isHost] = await Promise.all([currentSeatId(id), isHostOf(id)])
  const wantsOverride = parsed.data.override === true

  if (wantsOverride && !isHost) {
    return NextResponse.json(
      { error: 'not-host', message: 'Only the host can override a rejection.' },
      { status: 403 },
    )
  }

  if (seatId === null && !isHost) {
    return NextResponse.json(
      { error: 'no-seat', message: 'Join the room before picking.' },
      { status: 403 },
    )
  }

  // Turn order, enforced server-side. The host may pick out of turn, since
  // they are the one holding the phone that plays the music.
  const turn = await readTurn(id)
  const expired = turnHasExpired(turn?.turnStartedAt ?? null, room.settings.turnTimer)
  if (
    seatId !== null &&
    !isHost &&
    turn?.currentSeatId !== null &&
    turn?.currentSeatId !== seatId &&
    !expired
  ) {
    return NextResponse.json(
      { error: 'not-your-turn', message: "It is not your turn yet." },
      { status: 409 },
    )
  }

  try {
    const track = await fetchTrack(parsed.data.trackId)
    if (track === null) {
      return NextResponse.json(
        { error: 'no-track', message: 'Spotify has no track with that id.' },
        { status: 404 },
      )
    }

    const outcome = await submitPick({
      room,
      track,
      seatId,
      clientNonce: parsed.data.nonce,
      override: wantsOverride,
    })

    if (!outcome.ok) {
      // 422: the request was well-formed, the move was not legal.
      return NextResponse.json(
        {
          error: 'rejected',
          reason: outcome.result.valid ? null : outcome.result.reason,
          explanation: outcome.explanation,
        },
        { status: 422 },
      )
    }

    return NextResponse.json(
      {
        entry: outcome.entry,
        turn: outcome.turn,
        wasDuplicate: outcome.wasDuplicate,
        queueWarning: outcome.queueWarning,
      },
      { status: outcome.wasDuplicate ? 200 : 201 },
    )
  } catch (error) {
    return spotifyErrorResponse(error)
  }
}
